version: '2'
services:
  nginx-proxy:
    image: nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8088:8088"
    volumes:
      - ./data/acme.sh:/etc/acme.sh
      - ./data/nginx/certs:/etc/nginx/certs
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/app_protect:/var/log/app_protect
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - internal
      - webproxy
    logging:
      driver: json-file


  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: core-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy
    volumes:
      - ./data/nginx/certs:/etc/nginx/certs
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/acme.sh:/etc/acme.sh
    networks:
      - internal
    logging:
      driver: json-file

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
    networks:
      - internal
    logging:
      driver: json-file

networks:
    webproxy:
      external: true
    internal:

